language: ruby
rvm:
  - 2.1.10 # In security maintenance phase (will EOL soon!)
  - 2.2.6
  - 2.3.3
  - 2.4.0
addons:
    code_climate:
      repo_token: 0c1e171a171c155a28b285b4f51de50259744fdc720521df22a18d028774881d
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
